[workspace]
resolver = "3"
members = [
    "crates/bridge",
    "crates/core",
    "crates/front",
    "crates/runtime",
    "crates/sema",
    "crates/utils",
    "tool/rrc",
]

[profile.release]
lto = true
rpath = true

[profile.dev]
rpath = true
