name: MLIR Backend MultiArch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        llvm-version: [21, 22]
        os: [ubuntu-24.04, ubuntu-24.04-arm]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rust-src, rustfmt, clippy, rustc-dev, llvm-tools-preview

      - name: Setup GHC
        uses: haskell/ghcup-setup@v1
        with:
          ghc: 9.10.3
          cabal: latest

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build wget libgtest-dev libgmock-dev libspdlog-dev
          sudo pip install lit --break-system-packages
          cabal update

      - name: Install LLVM ${{ matrix.llvm-version }}
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh ${{ matrix.llvm-version }}
          sudo apt-get install -y \
            libmlir-${{ matrix.llvm-version }}-dev \
            mlir-${{ matrix.llvm-version }}-tools \
            llvm-${{ matrix.llvm-version }}-dev \
            llvm-${{ matrix.llvm-version }}-tools
          echo "LD_LIBRARY_PATH=/usr/lib/llvm-${{ matrix.llvm-version }}/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          variant: sccache
          key: ${{ matrix.os }}-${{ matrix.llvm-version }}

      - name: Configure CMake
        run: |
          env RUSTC_WRAPPER=sccache \
          cmake -B build \
          -G Ninja \
          -DLLVM_USE_LINKER=lld \
          -DCMAKE_CXX_COMPILER=clang++-${{ matrix.llvm-version }} \
          -DCMAKE_C_COMPILER=clang-${{ matrix.llvm-version }} \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DREUSSIR_ENABLE_PEDANTIC=ON \
          -DREUSSIR_ENABLE_TESTS=ON \
          -DCMAKE_C_COMPILER_LAUNCHER=sccache \
          -DCMAKE_CXX_COMPILER_LAUNCHER=sccache \
          -DLLVM_DIR=/usr/lib/llvm-${{ matrix.llvm-version }}/lib/cmake/llvm \
          -DMLIR_DIR=/usr/lib/llvm-${{ matrix.llvm-version }}/lib/cmake/mlir

      - name: Build
        run: cmake --build build --parallel

      - name: Run Unit Tests
        run: |
          cmake --build build --target reussir-ut
          ctest --test-dir build --output-on-failure

      - name: Run Integration Tests
        run: cmake --build build --target check

